### ISSUE TITLE
学習と生成を異なるデバイスで実行するとエラー出る

### ISSUE THREAD

**Issue by KateSawada** [KateSawada/musegan-pytorch#15]
不老で学習したものをデスクトップで使おうと思ったらload時にエラー．
全部のパラメーターのindexの先頭に `module.`がついてしまっている．

```
$ python generate.py -c config/generate.yml config/base.yml -m model/furo
Traceback (most recent call last):
  File "generate.py", line 183, in <module>
    generate(args, config)
  File "generate.py", line 123, in generate
    generator.load_state_dict(torch.load(config.pth))
  File "/home/ksawada/Documents/lab/lab_research/musegan-pytorch/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Generator:
        Missing key(s) in state_dict: "transconv0.transconv.weight", "transconv0.transconv.bias", "transconv0.batchnorm.weight", "transconv0.batchnorm.bias", "transconv0.batchnorm.running_mean", "transconv0.batchnorm.running_var", "transconv1.transconv.weight", "transconv1.transconv.bias", "transconv1.batchnorm.weight", "transconv1.batchnorm.bias", "transconv1.batchnorm.running_mean", "transconv1.batchnorm.running_var", "transconv2.transconv.weight", "transconv2.transconv.bias", "transconv2.batchnorm.weight", "transconv2.batchnorm.bias", "transconv2.batchnorm.running_mean", "transconv2.batchnorm.running_var", "transconv3.transconv.weight", "transconv3.transconv.bias", "transconv3.batchnorm.weight", "transconv3.batchnorm.bias", "transconv3.batchnorm.running_mean", "transconv3.batchnorm.running_var", "transconv4.0.transconv.weight", "transconv4.0.transconv.bias", "transconv4.0.batchnorm.weight", "transconv4.0.batchnorm.bias", "transconv4.0.batchnorm.running_mean", "transconv4.0.batchnorm.running_var", "transconv4.1.transconv.weight", "transconv4.1.transconv.bias", "transconv4.1.batchnorm.weight", "transconv4.1.batchnorm.bias", "transconv4.1.batchnorm.running_mean", "transconv4.1.batchnorm.running_var", "transconv4.2.transconv.weight", "transconv4.2.transconv.bias", "transconv4.2.batchnorm.weight", "transconv4.2.batchnorm.bias", "transconv4.2.batchnorm.running_mean", "transconv4.2.batchnorm.running_var", "transconv4.3.transconv.weight", "transconv4.3.transconv.bias", "transconv4.3.batchnorm.weight", "transconv4.3.batchnorm.bias", "transconv4.3.batchnorm.running_mean", "transconv4.3.batchnorm.running_var", "transconv4.4.transconv.weight", "transconv4.4.transconv.bias", "transconv4.4.batchnorm.weight", "transconv4.4.batchnorm.bias", "transconv4.4.batchnorm.running_mean", "transconv4.4.batchnorm.running_var", "transconv5.0.transconv.weight", "transconv5.0.transconv.bias", "transconv5.0.batchnorm.weight", "transconv5.0.batchnorm.bias", "transconv5.0.batchnorm.running_mean", "transconv5.0.batchnorm.running_var", "transconv5.1.transconv.weight", "transconv5.1.transconv.bias", "transconv5.1.batchnorm.weight", "transconv5.1.batchnorm.bias", "transconv5.1.batchnorm.running_mean", "transconv5.1.batchnorm.running_var", "transconv5.2.transconv.weight", "transconv5.2.transconv.bias", "transconv5.2.batchnorm.weight", "transconv5.2.batchnorm.bias", "transconv5.2.batchnorm.running_mean", "transconv5.2.batchnorm.running_var", "transconv5.3.transconv.weight", "transconv5.3.transconv.bias", "transconv5.3.batchnorm.weight", "transconv5.3.batchnorm.bias", "transconv5.3.batchnorm.running_mean", "transconv5.3.batchnorm.running_var", "transconv5.4.transconv.weight", "transconv5.4.transconv.bias", "transconv5.4.batchnorm.weight", "transconv5.4.batchnorm.bias", "transconv5.4.batchnorm.running_mean", "transconv5.4.batchnorm.running_var". 
        Unexpected key(s) in state_dict: "module.transconv0.transconv.weight", "module.transconv0.transconv.bias", "module.transconv0.batchnorm.weight", "module.transconv0.batchnorm.bias", "module.transconv0.batchnorm.running_mean", "module.transconv0.batchnorm.running_var", "module.transconv0.batchnorm.num_batches_tracked", "module.transconv1.transconv.weight", "module.transconv1.transconv.bias", "module.transconv1.batchnorm.weight", "module.transconv1.batchnorm.bias", "module.transconv1.batchnorm.running_mean", "module.transconv1.batchnorm.running_var", "module.transconv1.batchnorm.num_batches_tracked", "module.transconv2.transconv.weight", "module.transconv2.transconv.bias", "module.transconv2.batchnorm.weight", "module.transconv2.batchnorm.bias", "module.transconv2.batchnorm.running_mean", "module.transconv2.batchnorm.running_var", "module.transconv2.batchnorm.num_batches_tracked", "module.transconv3.transconv.weight", "module.transconv3.transconv.bias", "module.transconv3.batchnorm.weight", "module.transconv3.batchnorm.bias", "module.transconv3.batchnorm.running_mean", "module.transconv3.batchnorm.running_var", "module.transconv3.batchnorm.num_batches_tracked", "module.transconv4.0.transconv.weight", "module.transconv4.0.transconv.bias", "module.transconv4.0.batchnorm.weight", "module.transconv4.0.batchnorm.bias", "module.transconv4.0.batchnorm.running_mean", "module.transconv4.0.batchnorm.running_var", "module.transconv4.0.batchnorm.num_batches_tracked", "module.transconv4.1.transconv.weight", "module.transconv4.1.transconv.bias", "module.transconv4.1.batchnorm.weight", "module.transconv4.1.batchnorm.bias", "module.transconv4.1.batchnorm.running_mean", "module.transconv4.1.batchnorm.running_var", "module.transconv4.1.batchnorm.num_batches_tracked", "module.transconv4.2.transconv.weight", "module.transconv4.2.transconv.bias", "module.transconv4.2.batchnorm.weight", "module.transconv4.2.batchnorm.bias", "module.transconv4.2.batchnorm.running_mean", "module.transconv4.2.batchnorm.running_var", "module.transconv4.2.batchnorm.num_batches_tracked", "module.transconv4.3.transconv.weight", "module.transconv4.3.transconv.bias", "module.transconv4.3.batchnorm.weight", "module.transconv4.3.batchnorm.bias", "module.transconv4.3.batchnorm.running_mean", "module.transconv4.3.batchnorm.running_var", "module.transconv4.3.batchnorm.num_batches_tracked", "module.transconv4.4.transconv.weight", "module.transconv4.4.transconv.bias", "module.transconv4.4.batchnorm.weight", "module.transconv4.4.batchnorm.bias", "module.transconv4.4.batchnorm.running_mean", "module.transconv4.4.batchnorm.running_var", "module.transconv4.4.batchnorm.num_batches_tracked", "module.transconv5.0.transconv.weight", "module.transconv5.0.transconv.bias", "module.transconv5.0.batchnorm.weight", "module.transconv5.0.batchnorm.bias", "module.transconv5.0.batchnorm.running_mean", "module.transconv5.0.batchnorm.running_var", "module.transconv5.0.batchnorm.num_batches_tracked", "module.transconv5.1.transconv.weight", "module.transconv5.1.transconv.bias", "module.transconv5.1.batchnorm.weight", "module.transconv5.1.batchnorm.bias", "module.transconv5.1.batchnorm.running_mean", "module.transconv5.1.batchnorm.running_var", "module.transconv5.1.batchnorm.num_batches_tracked", "module.transconv5.2.transconv.weight", "module.transconv5.2.transconv.bias", "module.transconv5.2.batchnorm.weight", "module.transconv5.2.batchnorm.bias", "module.transconv5.2.batchnorm.running_mean", "module.transconv5.2.batchnorm.running_var", "module.transconv5.2.batchnorm.num_batches_tracked", "module.transconv5.3.transconv.weight", "module.transconv5.3.transconv.bias", "module.transconv5.3.batchnorm.weight", "module.transconv5.3.batchnorm.bias", "module.transconv5.3.batchnorm.running_mean", "module.transconv5.3.batchnorm.running_var", "module.transconv5.3.batchnorm.num_batches_tracked", "module.transconv5.4.transconv.weight", "module.transconv5.4.transconv.bias", "module.transconv5.4.batchnorm.weight", "module.transconv5.4.batchnorm.bias", "module.transconv5.4.batchnorm.running_mean", "module.transconv5.4.batchnorm.running_var", "module.transconv5.4.batchnorm.num_batches_tracked". 
```

**Comment by KateSawada** [comment]
原因: `torch.nn.DataParallel()`によって複数GPUに対応したモデルをsaveしたら，load時も同様に対応させないといけない
